version: '3.9'

services:
  api:
    image: node:20
    container_name: post-api
    working_dir: /app
    volumes:
      - .:/app
      - ./prisma/dev.db:/app/prisma/dev.db
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    environment:
      DATABASE_URL: "file:./prisma/dev.db"
